apiVersion: v1
kind: Pod
metadata:
  name: u18
spec:
  containers:
  - name: u18
    image: jackluxm/ubuntu18.04:v1
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-ce", "tail -f /dev/null"]
  imagePullSecrets:
          - name: regcred
